# Generated by Django 5.2.4 on 2025-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenaryoAnalizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senaryo_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senaryo Adı')),
                ('senaryo_metni', models.TextField(verbose_name='Senaryo Metni')),
                ('analiz_sonucu', models.TextField(verbose_name='Analiz Sonucu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Senaryo Analizi',
                'verbose_name_plural': 'Senaryo Analizleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
